# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.twig_extension:
        class: AppBundle\Twig\StatsExtension
        public: false
        arguments: ["@doctrine"]
        tags:
            - { name: twig.extension }

    app.googlequery:
        class: Carminato\GoogleCseBundle\Service\Query\ApiQuery
    app.googlerequest:
        class: Carminato\GoogleCseBundle\Service\ApiRequest

    app.kittyimages:
        class:     AppBundle\Service\KittyImageFetcher
        arguments: [%google.api_key%, %google.search_key%, @app.googlequery, @app.googlerequest, @doctrine.orm.default_result_cache]

    app.spam_validator:
        class:     AppBundle\Service\SpamValidator

    validator.is_not_spam:
        class: AppBundle\Validator\Constraints\IsNotSpamValidator
        arguments: [@app.spam_validator]
        tags:
            - { name: validator.constraint_validator }